### ISSUE TITLE
stanfordnmbl organization?

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/ScapulothoracicJointPlugin#1]
Might it make more sense to put this plugin in the stanfordnmbl organization? I view the `opensim-org` as related to the OpenSim software and not to research projects. The `opensim-metabolicsplugin` is not itself a research project. I guess the line is more grey than I had previously thought.

**Comment by aseth1** [comment]
Once the paper is out the "research" aspect is over and then I would like the plugin to be maintained along with OpenSim. Eventually, I think it will become a bult-in joint type, and so I though of keeping it closer to OpenSim than NMBL.

**Comment by chrisdembia** [comment]
Oh okay.
